version: '2.256'
catalog: Rancher-Internal 
  name: Jenkins-CC
  version: v0.1
  description: |
    Modify Jenkins to use a different listening port
  maintainer: Jeff Garcia <jeff.garcia@covered.ca.gov>
