version: '2'
catalog: Rancher-Internal 
  name: Jenkins-CC
  version: 2.256
  description: |
    Modify Jenkins to use a different listening port
  maintainer: Jeff Garcia <jeff.garcia@covered.ca.gov>
